### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Oswaldshoo** [DmitryCherneckiy/speech-to-text#2]
Once i run the file i got this error and i have all the required packages FileNotFoundError: [Errno 2] No such file or directory: 'file_30.wav'

**Comment by DmitryCherneckiy** [comment]
It looks like the error you encountered is not related to my code, as there is no reference to the file named 'file_30.wav' in my code. The error seems to be occurring elsewhere. To help you further, could you provide more details about the steps you took before encountering this error? In particular, let me know which file or operation is causing the problem and where in the code it is referenced. This will help me better understand the problem and make more accurate recommendations.

**Comment by Oswaldshoo** [comment]
I fixed it, it was a error on converting a audio format since I'm running it on Virtual env i didn't add path to ffmpeg. Thanks for being in touch.
